# Generated by Django 5.1.1 on 2024-09-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyWeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('time_epoch', models.BigIntegerField()),
                ('time', models.CharField(max_length=50)),
                ('temp_c', models.FloatField()),
                ('feelslike_c', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('condition_text', models.CharField(max_length=255)),
                ('chance_of_rain', models.IntegerField()),
            ],
        ),
    ]
