# Generated by Django 5.1.1 on 2024-09-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyweatherdata',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
